### ISSUE TITLE
Style Issues

### ISSUE THREAD

**Issue by ccpandhare** [sarthak-sehgal/frontend-101#1]
You've done great job on the first three tasks 👍 

But it wouldn't hurt to keep track of subtle style cues For instance, in A1-A3 the text doesn't appear centered (although you have technically centered it!) Also, you could consider using a sans-serif typeface as in the assignment. You may see it differently on your computer, which is because you haven't declared a typeface, and different browsers/OSs have different default typefaces!

**Comment by ccpandhare** [comment]
![screen shot](https://user-images.githubusercontent.com/20787612/32977658-c569b16c-cc57-11e7-84ab-9940b1010bd7.JPG)

**Comment by ccpandhare** [comment]
Also, @sarthak-sehgal add me as a collaborator!

**Comment by sarthak-sehgal** [comment]
Thank you for pointing that out!
@ccpandhare, please check whether the bug has been fixed in the latest commit.

**Comment by ccpandhare** [comment]
Good Work!
