### ISSUE TITLE
Review of Tasks B2, A4

### ISSUE THREAD

**Issue by ccpandhare** [sarthak-sehgal/frontend-101#2]
## Task B2 👍 
The clock hands in Assignment #B2 are all the same size. It would be good if you update that!
Apart from that, great work!!

## Task A4 🥇 
Excellent! I really liked the hamburger icon animation. Just a few things: 
- You could center the links in the responsive hamburger menu
- You could remove the black background from "Logo"

Apart from that – Excellent!

**Comment by sarthak-sehgal** [comment]
@ccpandhare, I have updated B2 and have centered the links in the responsive hamburger menu. Please have a look.
I will remove the black background from the logo as soon as I can.
Thank you for the feedback.

**Comment by ccpandhare** [comment]
Great! Feel free to close this issue now!
