### ISSUE TITLE
B1 Bug

### ISSUE THREAD

**Issue by ccpandhare** [sarthak-sehgal/frontend-101#5]
Hey
I wasn't able to run B1 on both Firefox and Chrome.
Please look into it!

**Comment by sarthak-sehgal** [comment]
Hey
B1 is not complete yet. Still under development. :)

**Comment by sarthak-sehgal** [comment]
B1 is now complete.
Hope you like it!

**Comment by ccpandhare** [comment]
Yup it works as expected now!
